version: 0.2

phases:
  pre_build:
    commands:
      - echo Install Packages...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files: '**/*'
